version: "3.7"

services:
  client:
    container_name: gym-client
    build: './client'
    command: npm run start
    environment:
      - PORT=8080
      - NODE_ENV=development
      - API_PORT=3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${CLIENT_HOST_PORT}:8080 

  api:
    container_name: gym-api
    build: ./api
    command: npm run start
    depends_on: 
      - mongo
    environment: 
      - WAIT_HOSTS=mongo:27017
      - PORT=3000
      - MONGO_USERNAME=${API_MONGO_USERNAME}
      - MONGO_PASSWORD=${API_MONGO_PASSWORD}
      - MONGO_database=api-gym
      - MONGO_PORT=27017
      - MONGO_SERVICE=mongo
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      - mongo-data:/data/db
    ports: 
      - ${API_HOST_PORT}:3000
      - ${API_HOST_DEBUG_PORT}:9229

  mongo: 
    container_name: gym-mongo
    image: mongo:4.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=api-gym
    ports:
      - ${MONGO_HOST_PORT}:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:${MONGO_EXPRESS_PORT}
    volumes:
      - mongo-data:/data/db
    depends_on: 
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo

volumes:
  mongo-data:      
