version: "3.7"

services:
  client:
    container_name: react-graphql-blueprint
    build: './client'
    command: npm run start
    environment:
      - PORT=8080
      - NODE_ENV=development
      - API_PORT=3000
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${CLIENT_HOST_PORT}:8080 

  api:
    container_name: graphql-node-blueprint-api
    build: ./api
    command: npm run start
    depends_on: 
      - mongo
    environment: 
      - WAIT_HOSTS=mongo:27017
      - PORT=3000
      - MONGO_USERNAME=${API_MONGO_USERNAME}
      - MONGO_PASSWORD=${API_MONGO_PASSWORD}
      - MONGO_database=api-graphql
      - MONGO_PORT=27017
      - MONGO_SERVICE=mongo
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      - mongo-data:/data/db
    ports: 
      - ${API_HOST_PORT}:3000
      - ${API_HOST_DEBUG_PORT}:9229

  mongo: 
    container_name: graphql-node-blueprint-mongo
    image: mongo:4.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=api-graphql
    ports:
      - ${MONGO_HOST_PORT}:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db

volumes:
  mongo-data:      
